### PR TITLE
New plugin architecture

### PR DESCRIPTION
**Pull request by matheuscmelo**
This PR is able to implement the new plugin architecture in the manager, making plugins installable.
In order to install a new plugin, use the endpoint docs from #70 .

https://docs.google.com/document/d/1M8eFmXoEXBSKTzI2y5ZzfwWPPxqN5p2gGsUhynho3G4/edit?usp=sharing

### CODE REVIEW

**Comment by matheuscmelo** [comment]
@liliarsampaio @javanlacerda @joseims

**Review by javanlacerda — APPROVED** [review]
This is a great contribution! Thanks! LGTM!

**Review by joseims — CHANGES_REQUESTED** [review]
I did approve the others but it's mandatory to update the endpoint doc's and also to create a document in the PR explaining how the plugin architecture works and how do you use it.

**Comment by matheuscmelo** [comment]
Just opened a new PR updating docs. #70

**Review by joseims — APPROVED** [review]
Still think there should be docs about the plugin architecture tho

**Review by liliarsampaio — APPROVED** [review]

**Pull request merged**
