### PR TITLE
Implement plugin persistence

### PR DESCRIPTION
**Pull request by matheuscmelo**
This PR is able to add plugin persistence to Manager

### CODE REVIEW

**Review by javanlacerda — CHANGES_REQUESTED** [review]
Please, test or remove the Etcd3PluginPersistence.

**Review by liliarsampaio — COMMENTED** [review]
I don't get Javan's request for the Etcd3Plugin. Why should it be deleted? Looks good otherwise. I'll wait on that reply to approve the PR.

**Comment by matheuscmelo** [comment]
@liliarsampaio @javanlacerda Persistence with Etcd3 was tested, it's working properly. Please review again.

**Review by javanlacerda — APPROVED** [review]
LGTM!

**Review by liliarsampaio — APPROVED** [review]

**Pull request merged**
